name: Release
on:
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        platform: [amd64, arm64, ppc64le, s390x]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check filesystem before
        run: |
          set -x
          ls
          cat config/helm/repos/stable/index.yaml
      - name: Checkout index.yaml from main branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: main
          sparse-checkout: config/helm/repos/stable/index.yaml
      - name: Check filesystem after
        run: |
          set -x
          ls
          cat config/helm/repos/stable/index.yaml